spring:
  kafka:
    producer:
      bootstrap-servers: my-kafka:9092
      acks: all

    consumer:
      bootstrap-servers: my-kafka:9092
    listener:
      type: batch
#      ack-mode: MANUAL_IMMEDIATE
#      type: single
